### ISSUE TITLE
master not working since last commit

### ISSUE THREAD

**Issue by mattwillsher** [voxpupuli/puppet-mrepo#13]
I get the following on puppet 3.3.2:

My site.pp:

```puppet
class { 'mrepo::params':
  src_root => '/srv/mrepo',
  selinux  => true,
}

mrepo::repo { 'centos6-x86_64':
  ensure    => present,
  update    => 'nightly',
  repotitle => 'CentOS 6 64 bit',
  arch      => 'x86_64',
  release   => '6.5',
  urls      => {
    addons      => 'rsync://mirrors.kernel.org/centos/$release/addons/$arch/',
    centosplus  => 'rsync://mirrors.kernel.org/centos/$release/centosplus/$arch/',
    updates     => 'rsync://mirrors.kernel.org/centos/$release/updates/$arch/',
  }
}
```

Error: Could not find resource 'Class[Mrepo::Repos]' for relationship from 'Class[Mrepo::Selinux]' on node localhost.guest.local
Error: Could not find resource 'Class[Mrepo::Repos]' for relationship from 'Class[Mrepo::Selinux]' on node localhost.guest.local

Any suggestions as to whats gone wrong? Thanks.

**Comment by alexjfisher** [comment]
@mattwillsher I'm going to close this issue as I believe it was fixed in https://github.com/voxpupuli/puppet-mrepo/pull/15

Please reopen if I'm mistaken.  Thanks.
