### ISSUE TITLE
Major version bump to remove older parameters

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-mrepo#43]
Using 'UNSET' for a parameter should be replaced with `undef`, but this would be a breaking change, but I think we're looking at a 2.0.0 first release under Vox so we should be fine 👍

**Comment by alexjfisher** [comment]
@petems I already bumped the version as I knew the function would no longer work with ruby 1.8 systems after the rubocop violations were fixed up.

**Comment by alexjfisher** [comment]
I'd spotted the interesting use of 'UNSET' too. https://github.com/voxpupuli/puppet-mrepo/pull/37#discussion_r78771718 ;)

**Comment by petems** [comment]
@alexjfisher Rad 👍

**Comment by petems** [comment]
Fixed in 5233b2ec6856e8708e3dfe6592ac16eb73154e06, closing
